config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about'=>'homes#about'
  devise_for :users
  resources :books, :only=>[:index,:show,:create,:edit,:update,:destroy]
  resources :users, :only=>[:index,:edit,:show,:update]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, length: { minimum: 1, maximum: 200 }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books,dependent: :destroy
  has_one_attached :profile_image

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50 }

  def get_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpg')
    end
      profile_image
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  # before_action :authenticate_user!

  def after_sign_in_path_for(resource)
   user_path(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :correct_user, only: [:edit, :update]

  def index
    @book=Book.new
    @user=current_user
    @books=Book.all

  end

  def create
    @book=Book.new(book_params)
    @book.user_id=current_user.id
    if @book.save
      flash[:success] = "successfully 投稿しました"
      redirect_to book_path(@book[:id])
    else
      flash[:danger]="error 投稿に失敗しました"
      @books=Book.all
      @user=current_user
      render :index
    end

  end

  def show
    @books=Book.find(params[:id])
    @user=@books.user
  end

  def edit
    @book=Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "successfully 更新に成功しました"
      redirect_to book_path(params[:id])
    else
      flash[:danger] = "error 更新に失敗しました"
      render :edit
    end
  end

  def destroy
    book=Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end

  def correct_user
    @book=Book.find(params[:id])
    @user=@book.user
    redirect_to books_path unless @user==current_user
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :correct_user ,only: [:edit,:update]

		def index
				@user=current_user
				@books=Book.new
				@users=User.all
		end



		def show
				@user=User.find(params[:id])
				@books=Book.new
				@book=@user.books
		end

		def edit
				@user=User.find(params[:id])
		end

		def update
				@user=User.find(params[:id])
				if @user.update(user_params)
					 flash[:success]= "successfully 更新に成功しました"
					redirect_to user_path(@user.id)
				else
					flash[:danger]= "error 更新に失敗しました"
					render :edit
				end
		end

		private

		def user_params
				params.require(:user).permit(:name,:introduction,:profile_image)
		end

		def correct_user
			@user=User.find(params[:id])
			redirect_to user_path(current_user.id) unless @user==current_user
		end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<%= flash[:danger] %>
<% if @book.errors.any? %>
 <%= @book.errors.count %>件のerrorが発生しました
 <ul>
   <% @book.errors.full_messages do each |message| %>
   <li><%= message %></li>
   <% end %>
 </ul>
 <% end %>
<div class="container">
  <div clas="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto pt-3">
      <h2>Editing Book</h2>
      <%= form_with model:@book, url:book_path(@book), method: :patch do |book| %>

      <label>
        Title</br>
        <%= book.text_field :title %>
      </label></br>
      <label>
        Option</br>
        <%= book.text_area :body %>
      </label></br>
      <input class="btn btn-sm btn-success" value="Update Book" type="submit">
      <% end %>
      <%= link_to "Show", book_path(@book) %> |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<%= flash[:danger] %>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <%= @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<div class="container pt-3">
    <div class="row">

      <%=render 'users/userinfo',user: @user,books: Book.new %>
      <div class="col-md-8 offset-md-1">

        <h3>Books</h3>
        <table>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Option</th>
            <th></th>
            <th></th>
          </tr>
          <% @books.each do |book| %>
          <tr>
            <td><%= link_to  user_path(book.user.id) do %>
            <%= image_tag book.user.get_image %>
            <% end %></td>
            <td><%= link_to book.title,book_path(book.id) %></td>
            <td><%= book.body %></td>
            <!--<td><%#= link_to 'show' ,book_path(book.id) %></td>-->
          </tr>
          <% end %>
        </table>
     </div>
   </div>
  </div>

app/views/books/show.html.erb
  <%= flash[:success] %>
  <dev class="container">
    <div class="row">
      <%=render 'users/userinfo',user: @user,books: Book.new %>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table>
           <tr>
            <th><%= image_tag @books.user.get_image %></br>
                <%= link_to @user.name, user_path(@user.id) %>
            </th>
            <th><%= @books.title %></th>
            <th><%= @books.body %></th>
            <% if @books.user == current_user %>
            <td><%= link_to 'Edit' ,edit_book_path(@books.id) ,class:'btn btn-primary' %></td>
            <td><%= link_to 'Destroy' ,book_path(@books.id) ,method: :delete ,class:'btn btn-danger' %></td>
            <% end %>
          </tr>
        </table>
      </div>
    </div>
  </dev>

app/views/homes/about.html.erb
<div class="container mt-3">
    <div class="row">
      <h1 class="px-3 mx-auto">Welcome to<i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
</div>

app/views/homes/top.html.erb
<main>
  <div class="container mt-3">
    <div class="row">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
        <h1 class="px-3 max-auto">welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
        <p>in <i class="fas fa-book"></i><strong>Bookers</strong>,</p>
        <p>you can share and exchange your opinions , inpressions , and emotions</p>
        <p>about various books!</p>

      <div class=" btn-wrapper col-10">
        <a class="btn btn-info btn-block btn-sm mb-3" href="/users/sign_in">Log in</a>
        <a class="btn btn-success btn-block btn-sm" href="/users/sign_up">Sign up</a>
      </div>
      </div>
      </div>
    </div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#Navbar"
       aria-controls="#Navbar" aria-expanded="true" aria-label="Toggle-navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="Navbar">

        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_path(current_user.id),class:"link" do %>
            <i class="fas fa-home"></i>Home
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path,class:"link" do %>
           <i class="fas fa-users"></i>Users
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to books_path,class:"link" do %>
          <i class="fas fa-book-open"></i>Books
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete,class:"link" do %>
          <i class="fas fa-sign-out-alt"></i>Log out
          <% end %>
        </li>
       <% else %>
        <li class="nav-item">
          <%= link_to root_path,class:"link" do %>
          <i class="fas fa-home"></i>Home
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to "/home/about",class:"link" do %>
          <i class="fas fa-link"></i>About
          <% end%>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path,class:"link" do %>
          <i class="fas fa-user-plus"></i>Sign up
          <% end %>
        </li>
       　<li class="nav-item">
          <%= link_to new_user_session_path,class:"link" do %>
          <i class="fas fa-sign-in-alt"></i>Log in
          </li>
          <% end %>
       <% end %>
       </ul>
      </div>
    </nav>

    <%= notice %>
    <%= yield %>
  </body>

  <footer>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>


  </footer>
</html>

app/views/users/_userinfo.html.erb
      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag user.get_image %>
        <table>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </table>

        <%= link_to edit_user_path(@user.id),class:"btn btn-outline-secondary btn-block mx-auto" do %>
          <i class="fas fa-user-cog"></i>
        <% end %>  
        <h2>New book</h2>
        <%= form_with model: books do |book| %>
        <label>
          Title</br>
          <%= book.text_field :title %>
        </label>
        <label>
          Option</br>
          <%= book.text_area :body %>
        </label>
        <input class="btn btn-success" type="submit" value="Create Book">
        <% end %>
      </div>

app/views/users/edit.html.erb
<%= flash[:danger] %>
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto pt-3">
      <h2>User info</h2></br>
      <%=form_with model:@user, url:user_path(@user), method: :patch do |user| %>
      <label>
        Name </br>
        <%= user.text_field :name %>
      </label></br>
      <label>
        Image </br>
        <%= user.file_field :profile_image, accept: "image/*" %>
      </label></br>
      <label>
        Introduction </br>
        <%= user.text_area :introduction %>
      </label></br>
      <input class="btn btn-sm btn-secondary", value="Update User", type="submit">
      <% end %>


    </div>
  </dev>
</div

app/views/users/index.html.erb
<div class="container pt-3">
  <!--<div class="col">-->
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <%= image_tag @user.get_image %>

        <table>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </table>

         <%= link_to edit_user_path(@user.id),class:"btn btn-outline-secondary btn-block mx-auto" do %>
          <i class="fas fa-user-cog"></i>
         <% end %>

        <h2>New book</h2>
        <%= form_with model: @books do |book| %>
        <label>
          Title</br>
          <%= book.text_field :title %>
        </label>
        <label>
          Option</br>
          <%= book.text_area :body %>
        </label>
        <input class="btn btn-success btn-sm" type="submit" value="Create Book">
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Users</h2>
        <table>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
          </tr>
          <% @users.each do |users| %>
          <tr>

            <td><%= image_tag users.get_image %></td>
            <td><%= users.name %></td>
            <td><%= link_to 'Show',user_path(users.id) %></td>

          </tr>
          <% end %>
        </table>
        </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= flash[:success] %>

<div class="container">
  <div class="row">
    <%=render 'users/userinfo',user: @user,books: @books %>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Option</th>
        </tr>
        <% @book.each do |book| %>
        <tr>
          <td><%=link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_image %>
          <% end %></td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body%></td>
        </tr>
        <% end %>
      </table>


    </div>
  </div>
</div>